name: Build+Test Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.0.0
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: build and test
        run: ./run_tests.sh
        shell: bash
